import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/template-parts/header'
import Footer from '@/components/template-parts/footer'
import { Providers } from './Redux/provider'
import Topbar from '@/components/template-parts/topbar/Topbar'
import Auth from '@/components/data/Auth'

const inter = Inter({ subsets: ['latin-ext'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="tr" className='h-full'>
      <body className={`h-full ${inter.className}`}>
        <Providers>
          <Auth />
          <Topbar />
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}