"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/template-parts/header'
import Footer from '@/components/template-parts/footer'
import { Providers } from './Redux/provider'
import Topbar from '@/components/template-parts/topbar/Topbar'
import Auth from '@/components/data/Auth'
import { getAccountDetail } from '@/components/data/query/query'
import store from './Redux/store'
import { restaurantsActions } from './Redux/features/restaurants-slice'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin-ext'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {



  const fetchSingleAccount = async (active_shop_account_idL) => {
    const accountD = await getAccountDetail(active_shop_account_idL);
    await store.dispatch(
      restaurantsActions.updateState({ activeCardAccount: accountD?.message })
    );
  };
  useEffect(() => {
    if (typeof window !== "undefined") {
      if (window.localStorage.getItem("active_shop_card_account")) {
        var active_shop_account_idL = JSON.parse(
          window.localStorage.getItem("active_shop_card_account")
        );
        fetchSingleAccount(active_shop_account_idL);
      }
    }
  }, []);

  // const fetchSingleAccount = async () => {
  //   if (typeof window !== "undefined") {
  //     if (window.localStorage.getItem("active_shop_card_account")) {
  //       var active_shop_account_idL = JSON.parse(
  //         window.localStorage.getItem("active_shop_card_account")
  //       );
  //     }
  //     const accountD = await getAccountDetail(active_shop_account_idL);
  //     store.dispatch(restaurantsActions.updateState({ activeCardAccount: accountD?.message }));
  //   }
  // };

  // useEffect(() => {
  //   fetchSingleAccount();
  // }, []);

  return (
    <html lang="tr" className='h-full'>
      <body className={`h-full ${inter.className}`}>
        <Providers>
          <Auth />
          <Topbar />
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}